2.02.62

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -56,5 +56,5 @@ jobs:
       - name: Smoke test
         working-directory: src
         run: |
-          out=$(./tt++ -V 2>&1 || true)
-          echo "$out" | grep -q 'TinTin++'
+          out=$(./tt++ -l validate 2>&1 || true)
+          echo "$out" | grep -q 'Invalid: zero'
